#!/bin/sh
# this script will search within the one-line description of lists of 4000 and 7400 cmos ICs
# set the folder containing the textfiles in $DIR
# 20151014 wotwot

if [ -z "$*" ] ; then
		echo "enter case insensitive search term"
		exit
fi

args="$*"

DIR=`dirname $0` # or whereever

cd $DIR || {
	echo "cant change to dir $DIR"
	exit
	}
echo "."
for i in $args ; do
	grep -i $i 7400.txt 4000.txt
done
