#!/bin/sh
# if you have a folder where you saved datasheets this will quickly search for filenames
# set this folder in $DIR
# 20151014 wotwot

if [ -z "$@" ] ; then
	echo "search what ?"
	exit
fi

DIR=`dirname $0`

cd $DIR

for i in $* ; do
		ls -l *$i*
done
